### ISSUE TITLE
Adding auto-reformatting to the master branch

### ISSUE THREAD

**Issue by tanmaymunjal** [civo/client-python#36]
Hey, so I recently setup auto-reformatting using black on my fork to make sure I sent in clean code for any PRs and also didn't have to do the code formatting manually myself.

I was just wondering if it would be a good idea to setup auto-reformatting on the master branch as well to maintain consistent code formatting. Or maybe we should add code style guide to the project and ask all contributors to follow it ig? 

Wdyt?

**Comment by alejandrojnm** [comment]
I just added an `.editorconfig` to the project
